### ISSUE TITLE
pretrained model of PointMetaBase-XXL on S3DIS 6-fold

### ISSUE THREAD

**Issue by HaoRan-hash** [linhaojia13/PointMetaBase#1]
<img width="580" alt="屏幕截图_20230216_142441" src="https://user-images.githubusercontent.com/54461374/219286182-3f428811-4bc9-4913-a448-e91ddd7ab853.png">
Pretrained model here is PointMetaBase-XL. Maybe you made a mistake? I hope you can correct it.

**Comment by linhaojia13** [comment]
Thank you for reminding me, I have corrected the link.
