### ISSUE TITLE
About the pretrained link for pointmetabase-xxl trained on scannet

### ISSUE THREAD

**Issue by liamlin5566** [linhaojia13/PointMetaBase#12]
Hello, thanks for sharing your great work.
I want to download the pretrained weight of  pointmetabase-xxl which is trained on scannet but the link seems to be for pointmetabase-xl. Can you provide the link for xxl?
Thank you.

**Comment by linhaojia13** [comment]
I apologize for the mistake. Here is the correct link for xxl: 
https://drive.google.com/file/d/1iD1m7QX-vvo-nGqPy1rPRe6-DWtnQhGu/view?usp=drive_link
