### ISSUE TITLE
Does the preprocessing method of data affect the accuracy of the network？

### ISSUE THREAD

**Issue by Yellowshuohahaha** [linhaojia13/PointMetaBase#13]
When pointnet++takes block input, randlanet takes sphere input, and repository takes the entire point cloud as input like point transformer. Does it affect the accuracy of the network？ Do you do some experiments?

**Comment by linhaojia13** [comment]
Yes, the preprocessing method will affect the accuracy significantly. I suggest you use Pointcept, which repoduce the sota methods well.

**Comment by mostafa501** [comment]
Hi @linhaojia13 i want to make preprocess for my data point clouds, can you please tell me how to do this.
thank you in advance.
