### ISSUE TITLE
About the torch seed configuration in the code

### ISSUE THREAD

**Issue by shenglandu** [linhaojia13/PointMetaBase#14]
Hi Haojia,

Thank you for your excellent work and the released code. I have a question regarding the torch seed configuration. In your code, you use different manual seeds for different models (e.g, pointmetabase-l ,pointmetabase-xl, pointmetabase-xxl). I wonder about your motivation behind this design, and how would the seeds influence the network training? Thanks a lot in advance. :)

Best

**Comment by linhaojia13** [comment]
On the S3DIS dataset, there's a significant variance in the final results, with fluctuations of about 1% mIoU. To report our results in a more fair and accurate manner, the results presented in the paper are the average values obtained under three random seed settings (1111, 2425, 4333). These three seeds were chosen arbitrarily and were not handpicked.
