### ISSUE TITLE
code version

### ISSUE THREAD

**Issue by 0belle** [linhaojia13/PointMetaBase#2]
could you release the code version only use python?

**Comment by linhaojia13** [comment]
In addition to Python code, this code repository also contains a basic library composed of some C++ codes. These libraries are designed to achieve efficient nearest neighbor search, downsampling, and other functions, and have been widely adopted by many open-source repositories for point cloud analysis. 
I'm sorry that I don't get the intention of your question. Are you encountering difficulties in compiling these libraries?

**Comment by 0belle** [comment]
I have some problems so that I cannot understand this network architecture, so I do not know how to change it in other dataset.  I do not know how to change .sh file and openpoints. May I get your email to describe my problem?    maybe so ridiculous..
