### ISSUE TITLE
Ablation study on S3DIS

### ISSUE THREAD

**Issue by FT-Zheng** [linhaojia13/PointMetaBase#4]
Thank you for releasing the source code of your excellent work :)
I found that there is a problem of center point filling in ballquery, which makes  it possible that some points in maxpooling redundant. Have you done the ablation study of hyperparameters nsample and radius in Ballquery on S3DIS data set? If so, could you share the results of the experiment?

**Comment by linhaojia13** [comment]
Thank you for your interest in our work! Unfortunately, I haven't conducted any ablation experiments related to Ballquery hyperparameters. As mentioned in the Readme, our code repository is built upon the [PointNeXt ](https://github.com/guochengqian/PointNeXt)code repository, and we inherited all experiment settings and hyperparameters from PointNeXt.

**Comment by FT-Zheng** [comment]
Thanks for your reply.
