### ISSUE TITLE
val on S3DIS but CUDA out of memory

### ISSUE THREAD

**Issue by FT-Zheng** [linhaojia13/PointMetaBase#5]
I tried to use KNN instead of Ballquery to find nearest neighbors (group_args['NAME'] == 'knn'). I used a single NVIDIA RTX 3090 24GB GPU and it occupied about 45% of the memory during training, but I encountered CUDA out of memory during validation. However, this situation did not occur when using Ballquery.

**Comment by linhaojia13** [comment]
Based on the experimental results you provided, it appears that the reason is that KNN requires more GPU memory compared to BallQuery. I'm sorry that we haven't explored anything about this ablation and therefore cannot provide any algorithmic suggestions. However, if feasible, you may consider conducting experiments using a GPU with a larger memory capacity.

**Comment by Lizhijian-123** [comment]
> Based on the experimental results you provided, it appears that the reason is that KNN requires more GPU memory compared to BallQuery. I'm sorry that we haven't explored anything about this ablation and therefore cannot provide any algorithmic suggestions. However, if feasible, you may consider conducting experiments using a GPU with a larger memory capacity.


How to not let the memory get smaller while validating? For example, I take up 20g of memory during training, but only 5g for verification. When verifying, my program is too small and is squeezed by others。GPU resources are not easy to grab。Thank you

**Comment by linhaojia13** [comment]
@Lizhijian-123 I'm sorry that I don't have any experience about this.

**Comment by FT-Zheng** [comment]
> Based on the experimental results you provided, it appears that the reason is that KNN requires more GPU memory compared to BallQuery. I'm sorry that we haven't explored anything about this ablation and therefore cannot provide any algorithmic suggestions. However, if feasible, you may consider conducting experiments using a GPU with a larger memory capacity.

I found that in the data processing of the training stage, voxel_max=24000, so the maximum number of points per scene is 24000. But the maximum number of points per scene during verification is about twice that of training, which may lead to a larger memory requirement when calculating KNN. Thank you for your answer, I will close this issue.
